### ISSUE TITLE
ssl_client_nonblock.c

### ISSUE THREAD

**Issue by denizgezmis** [darrenjs/openssl_examples#3]
Hi, 

I am not sure having "int nready;" which creates a variable in stack every time while loops is a good idea. Would be better to define those outside of loops..

Also, I am trying to save the outcome of server responses (fully, unencrypted, per line based) into a file for reviewing purposes. i.e.,
Client: CMD1 [CRLF]
Server: Response #1  [CRLF]  >> outfile.txt

Client: CMD2 [CRLF]
Response #2 [EOL] [CRLF]  >> outfile.txt
..

Tried quite a few few things but was not successful. Care to shed some light on?

**Comment by darrenjs** [comment]
Hi,

The `int nready` and also `int revents` are both defined in the loop. This could lead to a theoretical drop in efficiency, but in practice is negligble (and uses the same stack space on each loop). Instead the intent of the code is be demonstrative of using SSL, and so placing variables in the scope where they used leads, I believe, to more readible code (rather than the traditional C style of declaring all the variables are the start of the function).

As for trying to save the outcome of the server responses to file, I think what is happening is that your operating system is buffering the program output, and will only write to the file when the buffer is full.  To get around that, try running the server program via the `stdbuf` command (this is only applicable to Linux), example:

```console
stdbuf -o0  ./ssl_server_nonblock   > outfile
```

**Comment by denizgezmis** [comment]
Hi,

Agreed,. It was paying my two cents only. Thanks for the reply. What I am looking for is writing the buffer characters collected in the C program of CLIENT into file, each time command output collected, i.e, 
client sends CMD, once response fully received, write to file.

What I am able to obtain is arrays of DEFAULT_BUF_SIZE but not full command response, each time in common.h/print_unencrypted_data

BTW, I am using the client to communicate with an IMAP server.

Perhaps, IMAP protocol is sending the long responses in parts. Any further thoughts?

Cheers,

**Comment by darrenjs** [comment]
Hi,

The program is designed to consume only 64 bytes at a time of the inbound message.  So if a server application sends a 640 byte message, there will be ten calls to the `print_unencrypted_data` function, each passing a successive portion of the original message being transmitted.    

You could of course just change `DEFAULT_BUF_SIZE` to a large number, eg, 1 mb or something, and it is likely you will obtain the _"full command response"_ that you are after.  However, what happens on the day when the server sends a 2 mb sized message?  You will again get segmented callbacks.

Generally you should not assume in your client that you can receive all of the server response in a single transmission or callback.  You should handle the case when the original messages gets arbitrarily split up into smaller chunks.  The typical approach it so write a full decoder for the protocol (IMAP in your case), and use whatever headers fields may exist in the message to decode the message length.  So in your example, you could attempt to find out the length of the IMAP message being transmitted, and once that many bytes has been received and written to file, you can flush the file and/or close it, and prepare to receive any possible later messages.

**Comment by denizgezmis** [comment]
Sure, we are on the same page. Much appreciated all the feedback.
